version: "3.9"
services:

  postgres14:
    image: postgres:14.2
    environment:
      POSTGRES_DB: "company"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    ports:
      - "5432:5432"